### ISSUE TITLE
Validation sometimes doesn't help to locate the bug

### ISSUE THREAD

**Issue by gcasale** [radon-h2020/xopera-opera#15]
In xOpera SaaS it does help to have the run Validation option, but the
output in a number of occasions could be enhanced by indicating in
which relationship or node template the problem arises.

You can see an example attached, there is no entity called "str" and
one doesn't know where to start in debugging the issue.
![image (1)](https://user-images.githubusercontent.com/4592912/118395104-8d512680-b640-11eb-9f91-d2d2593e8f22.png)

**Comment by cankarm** [comment]
Frequently these errors result in typos in yaml or inputs. 

@sstanovnik, please check this issue.

**Comment by sstanovnik** [comment]
This was a regression introduced with xopera-api 0.4.1 and was fixed in [release 0.4.2 of xopera-api](https://github.com/xlab-si/xopera-api/releases/tag/0.4.2).

The scope of impact was from last Friday until fifteen minutes ago. Projects created in that timespan will continue to exhibit the issue. Newly created projects, as of fifteen minutes ago, incorporate the necessary fix.

Requesting close.
