### ISSUE TITLE
Project name clash

### ISSUE THREAD

**Issue by gcasale** [radon-h2020/xopera-opera#17]
The figure shows a situation where two workspaces have two projects with the same name (meetup02). The workspaces have different credentials. The deployment works fine in parallle, but there is overlap in the "Project outputs", the information shared is common across the two meetup02 projects, even though they are related only by the name.

![image](https://user-images.githubusercontent.com/4592912/118404477-f5b4fd80-b66a-11eb-9b1d-5a13ffa5137b.png)

**Comment by cankarm** [comment]
This issue has been observed and also reported on private xOpera SaaS gitlab page.  The fix is on the way - it seems that we will not allow creating projects with the same name. 

notify: @sstanovnik, @anzoman

**Comment by sstanovnik** [comment]
The resolution for this has just been deployed.

Existing projects with the same name will still exhibit the issue you've found. The only way around this is for you to recreate the projects, even using the same name. As far as security goes, this issue was only limited to a single user - having the same project name in two different users resulted in properly separated projects.

Requesting close.

**Comment by gcasale** [comment]
Approved
