### ISSUE TITLE
Ansible module dependency handling

### ISSUE THREAD

**Issue by duelle** [radon-h2020/xopera-opera#3]
When using an Ansible module like `docker_container` as done in https://github.com/radon-h2020/demo-ctt-sockshop/blob/master/radon-ctt/create_ti.yml#L6 I see an error like this:

> "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on <mypc>'s Python /<mygitpath>/radon-h2020/radon-ctt/ctt-server/.pyenv/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'"

Do I need to know all the Ansible module requirements beforehand to be able to install these on the target machines or what would be the best way to achieve the presence of all required tools/packages for the actual deployment?

**Comment by cankarm** [comment]
It seems that you rely on some python application that has requirements that you do not know beforehand?

This is strange. Usually python apps have "requirements.txt" which means you run "pip install requirements.txt" and you should be good to go.

**Comment by duelle** [comment]
My understanding of that error message was that the Ansible module "docker_container" requires that docker-py is installed on the destination system. As I am not directly interacting with Ansible (except writing the create.yml), how such dependencies are resolved and installed on the destination system. The system this was executed on had Docker installed already and was able to run that application without the said "docker-py" package. So it seems that this dependency is something due to the module used by Ansible.

**Comment by duelle** [comment]
Under the assumption that I define a VM using TOSCA and define a create.yml for the deployment of an application and I use some Ansible modules there (e.g., `docker_container`), that have requirements (e.g., the `pip`-package `docker-py` like here: https://docs.ansible.com/ansible/latest/modules/docker_container_module.html#requirements). Would I need to check the requirements of the modules and add an installation task for that requirements in the create.yml before using the actual module or what would be the way to go here?

**Comment by cankarm** [comment]
@duelle yes, I think that this is a way. Maybe @neza-vehovar or @anzoman can help with better idea.

**Comment by anzoman** [comment]
@cankarm thanks for the mention, @duelle I understand your concern and problems. Different Ansible modules require different prerequisites and one can easily forget to fulfil them all. So just as you suppose it's true that you cannot know what exactly is required for Ansible module to run successfully without errors. You just have to look for the requirements manually. And yes `docker_container` Ansible module assumes that you have docker installed and properly configured on your system before using it. 

So in your case the solution would be to ensure that docker in installed on a target system of the deployment. I suggest that you create a separate Ansible playbook where you install docker correctly like we do here: https://github.com/radon-h2020/demo-tosca-blueprint-openfaas/blob/master/system-installations-and-configurations/playbooks/docker/create.yml. This playbook installs docker on a target VM. This also means that we have a separate TOSCA node type definition just for the docker setup part as you can see here: https://github.com/radon-h2020/demo-tosca-blueprint-openfaas/blob/master/system-installations-and-configurations/system_preparation_opera_v1_3.yml. I believe that separating the setup part can bring you some benefits for the whole structure of the project and also for the orchestration process because you know exactly what task is under execution.

So you can give us some feedback what do you think of this proposed solution and also if you have any other second thoughts considering Ansible and xOpera just express them here or within other issues.

**Comment by duelle** [comment]
I think that Docker itself would be an comparably obvious prerequisite that might also be modeled in TOSCA when an application is packaged inside a Docker container. The point I was rather aiming at was the dependencies that Ansible itself has for its modules that are not that obvious (e.g., the `docker-py` package for the `docker_container` module). 
Can Ansible itself check (and possibly install) for missing dependencies for the used modules in a specified create.yml?

**Comment by cankarm** [comment]
The one who created the tasks should also add the task to install all dependencies - it might be a problem, that you face with a broken or low maintained Ansible module. Ansible engine by itself is just a tool which is as smart as the modules/playbooks are. It cannot _detect dependencies_ and install them if the a) software itself or b) application/module/playbook developer are not aware that those dependencies exists.

If only at _runtime_ you get such an error and realize that something is wrong, then you could maybe check this with the playbook and if the execution fails, you can install dependencies and try again.

**Comment by anzoman** [comment]
Yes as it was said, Ansible is designed in the way that leads you to install prerequisites before you use the module. Because it would be strange if you let Ansible just install those requirements to your target machine without exactly knowing which are those. Currently the Ansible documentation is your best friend to figure out what you need. It is possible that Ansible would change installing the requirements in the future but as things are right now I doubt so.  Ansible has a special module called [pip module](https://docs.ansible.com/ansible/latest/modules/pip_module.html) which helps you with the installation of the python package requirements within the playbooks and it is meant that you use this module to install the requirements (like docker-py) first and then use the desired module (like docker_container).

**Comment by duelle** [comment]
Then I'll include the installation of requirements into the create.yml to be sure that all dependencies are met. Thanks for your help!
