### ISSUE TITLE
Specify the location of the `.opera` folder (feature)

### ISSUE THREAD

**Issue by duelle** [radon-h2020/xopera-opera#5]
For our use case, it would be a nice feature if we could specify the location of the `.opera` folder as a paramter.
For example like this:
`opera --location /path/to/deployment_artifacts/sut deploy radon-ctt/sut.yml`

Which then would create the `.opera` folder into `/path/to/deployment_artifacts/sut/.opera` instead of the current/working directory.
That would allow us to use the same deployment artifacts (i.e. files) with several executions of opera without interference.

I assume that the other commands `undeploy` and `outputs` would then also need that parameter to know which deployment the command refers to.

**Comment by anzoman** [comment]
Hi, currently this is not possible but I think this is a good very idea for a new opera feature which could be really useful when testing multiple different deployments. What do you think @cankarm?

**Comment by anzoman** [comment]
@duelle I will propose this feature to opera and will let you know if this will be possible with further releases of opera.

**Comment by cankarm** [comment]
Hi, thanks for giving the ideas and keeping this thread alive. I was thinking and discussing this issue with my team, and it is obvious that this approach could solve some things. My concern is that this also allows to end up in strange states if people are a bit unorganized. It is possible to deploy with .opera in folder A, then deploy modified version with .opera in folder B, then un-deploy A only partially, as modifications are not incorporated, and at the end B is in inconsistent state as .opera content and reality are not the same. This might kill the statefullness of the approach if not used wisely. Sill I know many users that might find this helpful. Am I right @sstanovnik? :)

**Comment by sstanovnik** [comment]
Having the ability to relocate the `.opera/` folder is a great idea, imo, and something I've been wanting recently.

I seem to remember @anzoman saying that when specifying a service template that is _not_ in the current directory, opara still looks in the current directory for imports, instead of them being relative to the invoked file. That would be another extension to this idea: having an extra include path. It's a bit useless I think, as CSARs should be bundles, but could provide some flexibility.

The problems you've described aren't really problems, I don't think. Yes, you can get in trouble doing deployments with different templates, but you can also get in trouble writing `git reset --hard HEAD~100` on an unpushed branch. It's important for defaults to work the way you'd expect them too (i.e. not break things), but when you use extra options, you're responsible for vacuuming your own office. Maybe you want the office to go unvacuumed because you've lost your favourite coin? I think you should have a choice, but it _would_ be nice for opera to warn you about things it _can_ warn you about.

**Comment by anzoman** [comment]
This was resolved with the latest version of opera (0.5.8) where you will find an optional parameter `-p` or `--instance-path` which you can use not to relocate `.opera` folder but to replace it with another folder that opera orchestrator will use as its storage.

**Comment by duelle** [comment]
Sounds good. So one can specify an existing folder to use similarly to the usually created `.opera` folder?

**Comment by anzoman** [comment]
Yes exactly that :)

**Comment by duelle** [comment]
Great, thanks for you efforts, @anzoman
